# disable homebrew analytics
export HOMEBREW_NO_ANALYTICS=1

# custom prompt modified from the default ohmyzsh prompt
PROMPT=$'\n'
PROMPT+="%F{cyan}%c%f"
PROMPT+=$'\n'
PROMPT+="%(?:%F{green}➜ %f:%F{red}➜ %f)"

# history settings
export HISTFILE=~/.zhistory   # History savefile location
export HISTSIZE=1000000       # Number of history items to save in memory
export SAVEHIST=1000000       # Number of history items to save in file
setopt APPEND_HISTORY         # multiple sessions append to same history file (rather than last)
setopt HIST_IGNORE_ALL_DUPS   # when adding a new entry delete older duplicates
setopt HIST_IGNORE_DUPS       # don't add a new entry if it's an immediate duplicate
setopt INC_APPEND_HISTORY     # adds history incrementally to share it across sessions
setopt SHARE_HISTORY          # share history between sessions

# fancy history search using up/down arrows from ohmyzsh
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# custom aliases
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"
