" Detect OS. Result will be either Windows, Darwin, or Linux
if !exists("g:os")
    if has("win64") || has("win32") || has("win16")
        let g:os = "Windows"
    else
        let g:os = substitute(system('uname'), '\n', '', '')
    endif
endif

if g:os == "Darwin"
    set guifont=Menlo:h14

    if has("gui_macvim")
        " Skip loading MacVim colorscheme
        let macvim_skip_colorscheme=1

        " Press Ctrl-Tab to switch between open tabs (like browser tabs) to 
        " the right side. Ctrl-Shift-Tab goes the other way.
        noremap <C-Tab> :tabnext<CR>
        noremap <C-S-Tab> :tabprev<CR>

        " Switch to specific tab numbers with Command-number
        noremap <D-1> :tabn 1<CR>
        noremap <D-2> :tabn 2<CR>
        noremap <D-3> :tabn 3<CR>
        noremap <D-4> :tabn 4<CR>
        noremap <D-5> :tabn 5<CR>
        noremap <D-6> :tabn 6<CR>
        noremap <D-7> :tabn 7<CR>
        noremap <D-8> :tabn 8<CR>
        noremap <D-9> :tabn 9<CR>

        " Command-0 goes to the last tab
        noremap <D-0> :tablast<CR>
    endif

"elseif g:os == "Linux"
"    set guifont=Fira\ Mono\ 10
"elseif g:os == "Windows"
"    set guifont=Fira_Mono:h12:cANSI
endif


